// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9KmXAIWlhKyo_Wj1lL5QJN3Ar-VgNPYo',
    appId: '1:211278584844:web:453d63a127c6e06bfde229',
    messagingSenderId: '211278584844',
    projectId: 'boutiqa-59b91',
    authDomain: 'boutiqa-59b91.firebaseapp.com',
    storageBucket: 'boutiqa-59b91.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs2iqCr2mxysGbOAzifDPt3cTpwD44aUE',
    appId: '1:211278584844:android:ed554a71703ed043fde229',
    messagingSenderId: '211278584844',
    projectId: 'boutiqa-59b91',
    storageBucket: 'boutiqa-59b91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDctrZfrmy4qnYbYHXHuNlm5HLgjw4-Pes',
    appId: '1:211278584844:ios:8c38d5342514ad41fde229',
    messagingSenderId: '211278584844',
    projectId: 'boutiqa-59b91',
    storageBucket: 'boutiqa-59b91.appspot.com',
    iosBundleId: 'com.example.boutiqa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDctrZfrmy4qnYbYHXHuNlm5HLgjw4-Pes',
    appId: '1:211278584844:ios:8c38d5342514ad41fde229',
    messagingSenderId: '211278584844',
    projectId: 'boutiqa-59b91',
    storageBucket: 'boutiqa-59b91.appspot.com',
    iosBundleId: 'com.example.boutiqa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9KmXAIWlhKyo_Wj1lL5QJN3Ar-VgNPYo',
    appId: '1:211278584844:web:3c9c96324699ffadfde229',
    messagingSenderId: '211278584844',
    projectId: 'boutiqa-59b91',
    authDomain: 'boutiqa-59b91.firebaseapp.com',
    storageBucket: 'boutiqa-59b91.appspot.com',
  );

}